name: Saga
main: org.saga.Saga
version: 0.9
author: andf54
softdepend:
  - GroupManager
  - PermissionsEx
commands:
  a:
    description: Sends admin chat message.
    permission: saga.admin.chat
    usage: /<command> <message>.
